# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djeddit', '0013_auto_20190612_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
